services:
    rest.allTerritory:
        class: RestBundle\Service\AllTerritory
        arguments: [ "@doctrine.orm.entity_manager" ]

    rest.topAlbums:
        class: RestBundle\Service\TopAlbumsData
        arguments: [ "@doctrine.orm.entity_manager","@service_container"]

    rest.featuredArtist:
        class: RestBundle\Service\FeaturedArtist
        #arguments: ["@service_id", "plain_value", "%parameter%"]
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]


